/* Generated by Pyrex 0.9 on Thu Jul 15 01:26:10 2004 */

#include "Python.h"
#include "structmember.h"
#include "event.h"


static PyObject *__Pyx_UnpackItem(PyObject *, int); /*proto*/
static int __Pyx_EndUnpack(PyObject *, int); /*proto*/
static int __Pyx_PrintItem(PyObject *); /*proto*/
static int __Pyx_PrintNewline(void); /*proto*/
static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb); /*proto*/
static void __Pyx_ReRaise(void); /*proto*/
static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list); /*proto*/
static PyObject *__Pyx_GetExcValue(void); /*proto*/
static PyObject *__Pyx_GetName(PyObject *dict, char *name); /*proto*/
static int __Pyx_ArgTypeTest(PyObject *obj, PyTypeObject *type, int none_allowed, char *name); /*proto*/
static int __Pyx_TypeTest(PyObject *obj, PyTypeObject *type); /*proto*/
static int __Pyx_GetStarArgs(PyObject **args, PyObject **kwds, char *kwd_list[], int nargs, PyObject **args2, PyObject **kwds2); /*proto*/
static void __Pyx_WriteUnraisable(char *name); /*proto*/
static void __Pyx_AddTraceback(char *funcname); /*proto*/
static PyTypeObject *__Pyx_ImportType(char *module_name, char *class_name, long size);  /*proto*/
static int __Pyx_SetVtable(PyObject *dict, void *vtable); /*proto*/
static int __Pyx_GetVtable(PyObject *dict, void **vtabptr); /*proto*/

static PyObject *__pyx_m;
static PyObject *__pyx_b;
static int __pyx_lineno;
static char *__pyx_filename;
staticforward char **__pyx_f;

static char __pyx_mdoc[] = "event library\n\nThis module provides a mechanism to execute a function when a\nspecific event on a file handle, file descriptor, or signal occurs,\nor after a given time has passed.\n";

/* Declarations from event */

staticforward PyTypeObject __pyx_type_5event_event;

struct __pyx_obj_5event_event {
  PyObject_HEAD
  struct event ev;
  PyObject *callback;
  PyObject *arg;
  PyObject *handle;
};

static PyTypeObject *__pyx_ptype_5event_event = 0;
static int __pyx_v_5event___event_inited;
static PyObject *__pyx_k2;
static short __pyx_k3;
static PyObject *__pyx_k4;
static double __pyx_k5;
static double __pyx_k6;
static PyObject *__pyx_k7;
static int (__pyx_f_5event___event_sigcb(void)); /*proto*/
static void (__pyx_f_5event___event_handler(int ,short ,void (*))); /*proto*/

/* Implementation of event */

static char (__pyx_k1[]) = "sys";


static int __pyx_f_5event___event_sigcb(void) {
  int __pyx_r;

  /* "/misc/projects/pyevent/event.pyx":58 */
  __pyx_r = (-1);
  goto __pyx_L0;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_WriteUnraisable("event.__event_sigcb");
  __pyx_L0:;
  return __pyx_r;
}


static void __pyx_f_5event___event_handler(int __pyx_v_fd,short __pyx_v_evtype,void (*__pyx_v_arg)) {
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;

  /* "/misc/projects/pyevent/event.pyx":61 */
  __pyx_1 = (PyObject *)__pyx_v_arg;
  Py_INCREF(__pyx_1);
  __pyx_2 = PyObject_GetAttrString(__pyx_1, "__callback"); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 61; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyInt_FromLong(__pyx_v_evtype); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 61; goto __pyx_L1;}
  __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 61; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_1);
  __pyx_1 = 0;
  __pyx_1 = PyObject_CallObject(__pyx_2, __pyx_3); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 61; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_WriteUnraisable("event.__event_handler");
  __pyx_L0:;
}


static int __pyx_f_5event_5event___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_f_5event_5event___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_callback = 0;
  PyObject *__pyx_v_arg = 0;
  short __pyx_v_evtype;
  PyObject *__pyx_v_handle = 0;
  int __pyx_r;
  int __pyx_1;
  int __pyx_2;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  short __pyx_6;
  static char *__pyx_argnames[] = {"callback","arg","evtype","handle",0};
  __pyx_v_arg = __pyx_k2;
  __pyx_v_evtype = __pyx_k3;
  __pyx_v_handle = __pyx_k4;
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O|OhO", __pyx_argnames, &__pyx_v_callback, &__pyx_v_arg, &__pyx_v_evtype, &__pyx_v_handle)) return -1;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_callback);
  Py_INCREF(__pyx_v_arg);
  Py_INCREF(__pyx_v_handle);

  /* "/misc/projects/pyevent/event.pyx":81 */
  Py_INCREF(__pyx_v_callback);
  Py_DECREF(((struct __pyx_obj_5event_event *)__pyx_v_self)->callback);
  ((struct __pyx_obj_5event_event *)__pyx_v_self)->callback = __pyx_v_callback;

  /* "/misc/projects/pyevent/event.pyx":82 */
  Py_INCREF(__pyx_v_arg);
  Py_DECREF(((struct __pyx_obj_5event_event *)__pyx_v_self)->arg);
  ((struct __pyx_obj_5event_event *)__pyx_v_self)->arg = __pyx_v_arg;

  /* "/misc/projects/pyevent/event.pyx":83 */
  Py_INCREF(__pyx_v_handle);
  Py_DECREF(((struct __pyx_obj_5event_event *)__pyx_v_self)->handle);
  ((struct __pyx_obj_5event_event *)__pyx_v_self)->handle = __pyx_v_handle;

  /* "/misc/projects/pyevent/event.pyx":84 */
  __pyx_1 = (__pyx_v_evtype == 0);
  if (__pyx_1) {
    __pyx_2 = PyObject_IsTrue(__pyx_v_handle); if (__pyx_2 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 84; goto __pyx_L1;}
    __pyx_1 = (!__pyx_2);
  }
  if (__pyx_1) {

    /* "/misc/projects/pyevent/event.pyx":85 */
    evtimer_set((&((struct __pyx_obj_5event_event *)__pyx_v_self)->ev),__pyx_f_5event___event_handler,((void (*))__pyx_v_self));
    goto __pyx_L2;
  }
  __pyx_3 = PyInt_FromLong(__pyx_v_evtype); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 86; goto __pyx_L1;}
  __pyx_4 = __Pyx_GetName(__pyx_m, "EV_SIGNAL"); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 86; goto __pyx_L1;}
  if (PyObject_Cmp(__pyx_3, __pyx_4, &__pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 86; goto __pyx_L1;}
  __pyx_2 = __pyx_2 == 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  if (__pyx_2) {

    /* "/misc/projects/pyevent/event.pyx":87 */
    __pyx_3 = PyInt_FromLong(__pyx_v_evtype); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 87; goto __pyx_L1;}
    __pyx_4 = __Pyx_GetName(__pyx_m, "EV_PERSIST"); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 87; goto __pyx_L1;}
    __pyx_5 = PyNumber_Or(__pyx_3, __pyx_4); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 87; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __pyx_6 = PyInt_AsLong(__pyx_5); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 87; goto __pyx_L1;}
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    __pyx_v_evtype = __pyx_6;

    /* "/misc/projects/pyevent/event.pyx":88 */
    __pyx_1 = PyInt_AsLong(__pyx_v_handle); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 88; goto __pyx_L1;}
    event_set((&((struct __pyx_obj_5event_event *)__pyx_v_self)->ev),__pyx_1,__pyx_v_evtype,__pyx_f_5event___event_handler,((void (*))__pyx_v_self));
    goto __pyx_L2;
  }
  /*else*/ {

    /* "/misc/projects/pyevent/event.pyx":90 */
    __pyx_3 = __Pyx_GetName(__pyx_b, "type"); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 90; goto __pyx_L1;}
    __pyx_4 = PyTuple_New(1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 90; goto __pyx_L1;}
    Py_INCREF(__pyx_v_handle);
    PyTuple_SET_ITEM(__pyx_4, 0, __pyx_v_handle);
    __pyx_5 = PyObject_CallObject(__pyx_3, __pyx_4); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 90; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __pyx_3 = __Pyx_GetName(__pyx_b, "int"); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 90; goto __pyx_L1;}
    if (PyObject_Cmp(__pyx_5, __pyx_3, &__pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 90; goto __pyx_L1;}
    __pyx_2 = __pyx_2 != 0;
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    if (__pyx_2) {

      /* "/misc/projects/pyevent/event.pyx":91 */
      __pyx_4 = PyObject_GetAttrString(__pyx_v_handle, "fileno"); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 91; goto __pyx_L1;}
      __pyx_5 = PyTuple_New(0); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 91; goto __pyx_L1;}
      __pyx_3 = PyObject_CallObject(__pyx_4, __pyx_5); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 91; goto __pyx_L1;}
      Py_DECREF(__pyx_4); __pyx_4 = 0;
      Py_DECREF(__pyx_5); __pyx_5 = 0;
      Py_DECREF(__pyx_v_handle);
      __pyx_v_handle = __pyx_3;
      __pyx_3 = 0;
      goto __pyx_L3;
    }
    __pyx_L3:;

    /* "/misc/projects/pyevent/event.pyx":92 */
    __pyx_1 = PyInt_AsLong(__pyx_v_handle); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 92; goto __pyx_L1;}
    event_set((&((struct __pyx_obj_5event_event *)__pyx_v_self)->ev),__pyx_1,__pyx_v_evtype,__pyx_f_5event___event_handler,((void (*))__pyx_v_self));
  }
  __pyx_L2:;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  __Pyx_AddTraceback("event.event.__init__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_callback);
  Py_DECREF(__pyx_v_arg);
  Py_DECREF(__pyx_v_handle);
  return __pyx_r;
}


static PyObject *__pyx_f_5event_5event___callback(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_5event_5event___callback(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_evtype = 0;
  extern int event_gotsig;
  extern int ((*event_sigcb)(void));
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  int __pyx_4;
  int __pyx_5;
  static char *__pyx_argnames[] = {"evtype",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_evtype)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_evtype);

  /* "/misc/projects/pyevent/event.pyx":98 */
  /*try:*/ {

    /* "/misc/projects/pyevent/event.pyx":99 */
    __pyx_1 = PyTuple_New(4); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 99; goto __pyx_L2;}
    Py_INCREF(__pyx_v_self);
    PyTuple_SET_ITEM(__pyx_1, 0, __pyx_v_self);
    Py_INCREF(((struct __pyx_obj_5event_event *)__pyx_v_self)->handle);
    PyTuple_SET_ITEM(__pyx_1, 1, ((struct __pyx_obj_5event_event *)__pyx_v_self)->handle);
    Py_INCREF(__pyx_v_evtype);
    PyTuple_SET_ITEM(__pyx_1, 2, __pyx_v_evtype);
    Py_INCREF(((struct __pyx_obj_5event_event *)__pyx_v_self)->arg);
    PyTuple_SET_ITEM(__pyx_1, 3, ((struct __pyx_obj_5event_event *)__pyx_v_self)->arg);
    __pyx_2 = PyObject_CallObject(((struct __pyx_obj_5event_event *)__pyx_v_self)->callback, __pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 99; goto __pyx_L2;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    Py_DECREF(__pyx_2); __pyx_2 = 0;

    /* "/misc/projects/pyevent/event.pyx":100 */
    __pyx_1 = PyObject_GetAttrString(__pyx_v_self, "pending"); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 100; goto __pyx_L2;}
    __pyx_2 = PyTuple_New(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 100; goto __pyx_L2;}
    __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 100; goto __pyx_L2;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_4 = PyObject_IsTrue(__pyx_3); if (__pyx_4 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 100; goto __pyx_L2;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __pyx_5 = (!__pyx_4);
    if (__pyx_5) {

      /* "/misc/projects/pyevent/event.pyx":101 */
      Py_DECREF(__pyx_v_self);
      goto __pyx_L4;
    }
    __pyx_L4:;
  }
  goto __pyx_L3;
  __pyx_L2:;
  Py_XDECREF(__pyx_1); __pyx_1 = 0;
  Py_XDECREF(__pyx_2); __pyx_2 = 0;
  Py_XDECREF(__pyx_3); __pyx_3 = 0;

  /* "/misc/projects/pyevent/event.pyx":102 */
  /*except:*/ {
    __Pyx_AddTraceback("event.__callback");
    __pyx_1 = __Pyx_GetExcValue(); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 102; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;

    /* "/misc/projects/pyevent/event.pyx":103 */
    event_sigcb = __pyx_f_5event___event_sigcb;

    /* "/misc/projects/pyevent/event.pyx":104 */
    event_gotsig = 1;

    /* "/misc/projects/pyevent/event.pyx":105 */
    __pyx_2 = __Pyx_GetName(__pyx_m, "sys"); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 105; goto __pyx_L1;}
    __pyx_3 = PyObject_GetAttrString(__pyx_2, "exc_info"); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 105; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_1 = PyTuple_New(0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 105; goto __pyx_L1;}
    __pyx_2 = PyObject_CallObject(__pyx_3, __pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 105; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    if (PyObject_SetAttrString(__pyx_m, "__event_exc", __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 105; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    goto __pyx_L3;
  }
  __pyx_L3:;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("event.event.__callback");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_evtype);
  return __pyx_r;
}


static PyObject *__pyx_f_5event_5event_add(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_5event_5event_add[] = "Add event to be executed after an optional timeout.\n\n        Arguments:\n        \n        timeout -- seconds after which the event will be executed\n        ";
static PyObject *__pyx_f_5event_5event_add(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  double __pyx_v_timeout;
  struct timeval __pyx_v_tv;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  int __pyx_4;
  int __pyx_5;
  static char *__pyx_argnames[] = {"timeout",0};
  __pyx_v_timeout = __pyx_k5;
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "|d", __pyx_argnames, &__pyx_v_timeout)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/misc/projects/pyevent/event.pyx":116 */
  __pyx_1 = PyObject_GetAttrString(__pyx_v_self, "pending"); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 116; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 116; goto __pyx_L1;}
  __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 116; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_4 = PyObject_IsTrue(__pyx_3); if (__pyx_4 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 116; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_5 = (!__pyx_4);
  if (__pyx_5) {

    /* "/misc/projects/pyevent/event.pyx":117 */
    Py_INCREF(__pyx_v_self);
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/misc/projects/pyevent/event.pyx":118 */
  __pyx_4 = (__pyx_v_timeout > 0.0);
  if (__pyx_4) {

    /* "/misc/projects/pyevent/event.pyx":119 */
    __pyx_v_tv.tv_sec = ((long )__pyx_v_timeout);

    /* "/misc/projects/pyevent/event.pyx":120 */
    __pyx_v_tv.tv_usec = ((__pyx_v_timeout - ((double )__pyx_v_timeout)) * 1000000.0);

    /* "/misc/projects/pyevent/event.pyx":121 */
    event_add((&((struct __pyx_obj_5event_event *)__pyx_v_self)->ev),(&__pyx_v_tv));
    goto __pyx_L3;
  }
  /*else*/ {

    /* "/misc/projects/pyevent/event.pyx":123 */
    event_add((&((struct __pyx_obj_5event_event *)__pyx_v_self)->ev),0);
  }
  __pyx_L3:;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("event.event.add");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}


static PyObject *__pyx_f_5event_5event_pending(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_5event_5event_pending[] = "Return 1 if the event is scheduled to run, or else 0.";
static PyObject *__pyx_f_5event_5event_pending(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  short __pyx_4;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/misc/projects/pyevent/event.pyx":127 */
  __pyx_1 = __Pyx_GetName(__pyx_m, "EV_TIMEOUT"); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 127; goto __pyx_L1;}
  __pyx_2 = __Pyx_GetName(__pyx_m, "EV_SIGNAL"); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 127; goto __pyx_L1;}
  __pyx_3 = PyNumber_Or(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 127; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_1 = __Pyx_GetName(__pyx_m, "EV_READ"); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 127; goto __pyx_L1;}
  __pyx_2 = PyNumber_Or(__pyx_3, __pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 127; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_3 = __Pyx_GetName(__pyx_m, "EV_WRITE"); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 127; goto __pyx_L1;}
  __pyx_1 = PyNumber_Or(__pyx_2, __pyx_3); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 127; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_4 = PyInt_AsLong(__pyx_1); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 127; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_2 = PyInt_FromLong(event_pending((&((struct __pyx_obj_5event_event *)__pyx_v_self)->ev),__pyx_4,0)); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 127; goto __pyx_L1;}
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("event.event.pending");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}


static PyObject *__pyx_f_5event_5event_delete(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_5event_5event_delete[] = "Remove event from the event queue.";
static PyObject *__pyx_f_5event_5event_delete(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  int __pyx_4;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/misc/projects/pyevent/event.pyx":131 */
  __pyx_1 = PyObject_GetAttrString(__pyx_v_self, "pending"); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 131; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 131; goto __pyx_L1;}
  __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 131; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_4 = PyObject_IsTrue(__pyx_3); if (__pyx_4 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 131; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  if (__pyx_4) {

    /* "/misc/projects/pyevent/event.pyx":132 */
    event_del((&((struct __pyx_obj_5event_event *)__pyx_v_self)->ev));

    /* "/misc/projects/pyevent/event.pyx":133 */
    Py_DECREF(__pyx_v_self);
    goto __pyx_L2;
  }
  __pyx_L2:;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("event.event.delete");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}


static void __pyx_f_5event_5event___dealloc__(PyObject *__pyx_v_self); /*proto*/
static void __pyx_f_5event_5event___dealloc__(PyObject *__pyx_v_self) {
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  Py_INCREF(__pyx_v_self);

  /* "/misc/projects/pyevent/event.pyx":136 */
  __pyx_1 = PyObject_GetAttrString(__pyx_v_self, "delete"); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 136; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 136; goto __pyx_L1;}
  __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 136; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("event.event.__dealloc__");
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
}

static char (__pyx_k8[]) = "<event flags=0x%x, handle=%s, callback=%s, arg=%s>";

static PyObject *__pyx_f_5event_5event___repr__(PyObject *__pyx_v_self); /*proto*/
static PyObject *__pyx_f_5event_5event___repr__(PyObject *__pyx_v_self) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  Py_INCREF(__pyx_v_self);

  /* "/misc/projects/pyevent/event.pyx":139 */
  __pyx_1 = PyString_FromString(__pyx_k8); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 139; goto __pyx_L1;}
  __pyx_2 = PyInt_FromLong(((struct __pyx_obj_5event_event *)__pyx_v_self)->ev.ev_flags); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 140; goto __pyx_L1;}
  __pyx_3 = PyTuple_New(4); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 140; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_2);
  Py_INCREF(((struct __pyx_obj_5event_event *)__pyx_v_self)->handle);
  PyTuple_SET_ITEM(__pyx_3, 1, ((struct __pyx_obj_5event_event *)__pyx_v_self)->handle);
  Py_INCREF(((struct __pyx_obj_5event_event *)__pyx_v_self)->callback);
  PyTuple_SET_ITEM(__pyx_3, 2, ((struct __pyx_obj_5event_event *)__pyx_v_self)->callback);
  Py_INCREF(((struct __pyx_obj_5event_event *)__pyx_v_self)->arg);
  PyTuple_SET_ITEM(__pyx_3, 3, ((struct __pyx_obj_5event_event *)__pyx_v_self)->arg);
  __pyx_2 = 0;
  __pyx_2 = PyNumber_Remainder(__pyx_1, __pyx_3); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 139; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("event.event.__repr__");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}


static PyObject *__pyx_f_5event_init(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_5event_init[] = "Initialize event queue.";
static PyObject *__pyx_f_5event_init(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v___event_inited;
  PyObject *__pyx_r;
  int __pyx_1;
  int __pyx_2;
  PyObject *__pyx_3 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  __pyx_v___event_inited = Py_None; Py_INCREF(__pyx_v___event_inited);

  /* "/misc/projects/pyevent/event.pyx":144 */
  __pyx_1 = PyObject_IsTrue(__pyx_v___event_inited); if (__pyx_1 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 144; goto __pyx_L1;}
  __pyx_2 = (!__pyx_1);
  if (__pyx_2) {

    /* "/misc/projects/pyevent/event.pyx":145 */
    event_init();

    /* "/misc/projects/pyevent/event.pyx":146 */
    __pyx_3 = PyInt_FromLong(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 146; goto __pyx_L1;}
    Py_DECREF(__pyx_v___event_inited);
    __pyx_v___event_inited = __pyx_3;
    __pyx_3 = 0;
    goto __pyx_L2;
  }
  __pyx_L2:;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("event.init");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v___event_inited);
  return __pyx_r;
}


static PyObject *__pyx_f_5event_add(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_5event_add[] = "Add the specified event to the event queue, with an optional timeout.";
static PyObject *__pyx_f_5event_add(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  struct __pyx_obj_5event_event *__pyx_v_ev = 0;
  double __pyx_v_timeout;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  static char *__pyx_argnames[] = {"ev","timeout",0};
  __pyx_v_timeout = __pyx_k6;
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O|d", __pyx_argnames, &__pyx_v_ev, &__pyx_v_timeout)) return 0;
  Py_INCREF(__pyx_v_ev);
  if (!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_ev), __pyx_ptype_5event_event, 1, "ev")) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 148; goto __pyx_L1;}

  /* "/misc/projects/pyevent/event.pyx":150 */
  __pyx_1 = PyObject_GetAttrString(((PyObject *)__pyx_v_ev), "add"); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 150; goto __pyx_L1;}
  __pyx_2 = PyFloat_FromDouble(__pyx_v_timeout); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 150; goto __pyx_L1;}
  __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 150; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_2);
  __pyx_2 = 0;
  __pyx_2 = PyObject_CallObject(__pyx_1, __pyx_3); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 150; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("event.add");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_ev);
  return __pyx_r;
}


static PyObject *__pyx_f_5event_delete(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_5event_delete[] = "Delete the specified event.";
static PyObject *__pyx_f_5event_delete(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  struct __pyx_obj_5event_event *__pyx_v_ev = 0;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  static char *__pyx_argnames[] = {"ev",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_ev)) return 0;
  Py_INCREF(__pyx_v_ev);
  if (!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_ev), __pyx_ptype_5event_event, 1, "ev")) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 152; goto __pyx_L1;}

  /* "/misc/projects/pyevent/event.pyx":154 */
  __pyx_1 = PyObject_GetAttrString(((PyObject *)__pyx_v_ev), "delete"); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 154; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 154; goto __pyx_L1;}
  __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 154; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("event.delete");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_ev);
  return __pyx_r;
}


static PyObject *__pyx_f_5event_dispatch(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_5event_dispatch[] = "Dispatch all events on the event queue.";
static PyObject *__pyx_f_5event_dispatch(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  int __pyx_2;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  PyObject *__pyx_6 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;

  /* "/misc/projects/pyevent/event.pyx":159 */
  event_dispatch();

  /* "/misc/projects/pyevent/event.pyx":160 */
  __pyx_1 = __Pyx_GetName(__pyx_m, "__event_exc"); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 160; goto __pyx_L1;}
  __pyx_2 = PyObject_IsTrue(__pyx_1); if (__pyx_2 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 160; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  if (__pyx_2) {

    /* "/misc/projects/pyevent/event.pyx":161 */
    __pyx_1 = __Pyx_GetName(__pyx_m, "__event_exc"); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 161; goto __pyx_L1;}
    __pyx_3 = PyInt_FromLong(0); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 161; goto __pyx_L1;}
    __pyx_4 = PyObject_GetItem(__pyx_1, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 161; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __pyx_1 = __Pyx_GetName(__pyx_m, "__event_exc"); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 161; goto __pyx_L1;}
    __pyx_3 = PyInt_FromLong(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 161; goto __pyx_L1;}
    __pyx_5 = PyObject_GetItem(__pyx_1, __pyx_3); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 161; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __pyx_1 = __Pyx_GetName(__pyx_m, "__event_exc"); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 161; goto __pyx_L1;}
    __pyx_3 = PyInt_FromLong(2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 161; goto __pyx_L1;}
    __pyx_6 = PyObject_GetItem(__pyx_1, __pyx_3); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 161; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __Pyx_Raise(__pyx_4, __pyx_5, __pyx_6);
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    Py_DECREF(__pyx_6); __pyx_6 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 161; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  Py_XDECREF(__pyx_6);
  __Pyx_AddTraceback("event.dispatch");
  __pyx_r = 0;
  __pyx_L0:;
  return __pyx_r;
}


static PyObject *__pyx_f_5event_loop(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_5event_loop[] = "Dispatch all pending events on queue in a single pass.";
static PyObject *__pyx_f_5event_loop(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_nonblock = 0;
  int __pyx_v_flags;
  PyObject *__pyx_r;
  int __pyx_1;
  static char *__pyx_argnames[] = {"nonblock",0};
  __pyx_v_nonblock = __pyx_k7;
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "|O", __pyx_argnames, &__pyx_v_nonblock)) return 0;
  Py_INCREF(__pyx_v_nonblock);

  /* "/misc/projects/pyevent/event.pyx":166 */
  __pyx_v_flags = EVLOOP_ONCE;

  /* "/misc/projects/pyevent/event.pyx":167 */
  __pyx_1 = PyObject_IsTrue(__pyx_v_nonblock); if (__pyx_1 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 167; goto __pyx_L1;}
  if (__pyx_1) {

    /* "/misc/projects/pyevent/event.pyx":168 */
    __pyx_v_flags = (EVLOOP_ONCE | EVLOOP_NONBLOCK);
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/misc/projects/pyevent/event.pyx":169 */
  event_loop(__pyx_v_flags);

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("event.loop");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_nonblock);
  return __pyx_r;
}

static PyObject *__pyx_tp_new_5event_event(struct _typeobject *t, PyObject *a, PyObject *k) {
  PyObject *o = (*t->tp_alloc)(t, 0);
  struct __pyx_obj_5event_event *p = (struct __pyx_obj_5event_event *)o;
  p->callback = Py_None; Py_INCREF(p->callback);
  p->arg = Py_None; Py_INCREF(p->arg);
  p->handle = Py_None; Py_INCREF(p->handle);
  return o;
}

static void __pyx_tp_dealloc_5event_event(PyObject *o) {
  struct __pyx_obj_5event_event *p = (struct __pyx_obj_5event_event *)o;
  {
    PyObject *etype, *eval, *etb;
    PyErr_Fetch(&etype, &eval, &etb);
    ++o->ob_refcnt;
    __pyx_f_5event_5event___dealloc__(o);
    if (PyErr_Occurred()) PyErr_WriteUnraisable(o);
    --o->ob_refcnt;
    PyErr_Restore(etype, eval, etb);
  }
  Py_XDECREF(p->callback);
  Py_XDECREF(p->arg);
  Py_XDECREF(p->handle);
  (*o->ob_type->tp_free)(o);
}

static int __pyx_tp_traverse_5event_event(PyObject *o, visitproc v, void *a) {
  int e;
  struct __pyx_obj_5event_event *p = (struct __pyx_obj_5event_event *)o;
  e = (*v)(p->callback, a); if (e) return e;
  e = (*v)(p->arg, a); if (e) return e;
  e = (*v)(p->handle, a); if (e) return e;
  return 0;
}

static int __pyx_tp_clear_5event_event(PyObject *o) {
  struct __pyx_obj_5event_event *p = (struct __pyx_obj_5event_event *)o;
  Py_XDECREF(p->callback);
  p->callback = Py_None; Py_INCREF(p->callback);
  Py_XDECREF(p->arg);
  p->arg = Py_None; Py_INCREF(p->arg);
  Py_XDECREF(p->handle);
  p->handle = Py_None; Py_INCREF(p->handle);
  return 0;
}

static struct PyMethodDef __pyx_methods_5event_event[] = {
  {"__callback", (PyCFunction)__pyx_f_5event_5event___callback, METH_VARARGS|METH_KEYWORDS, 0},
  {"add", (PyCFunction)__pyx_f_5event_5event_add, METH_VARARGS|METH_KEYWORDS, __pyx_doc_5event_5event_add},
  {"pending", (PyCFunction)__pyx_f_5event_5event_pending, METH_VARARGS|METH_KEYWORDS, __pyx_doc_5event_5event_pending},
  {"delete", (PyCFunction)__pyx_f_5event_5event_delete, METH_VARARGS|METH_KEYWORDS, __pyx_doc_5event_5event_delete},
  {0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_event = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
};

static PySequenceMethods __pyx_tp_as_sequence_event = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_event = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_event = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

statichere PyTypeObject __pyx_type_5event_event = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "event.event", /*tp_name*/
  sizeof(struct __pyx_obj_5event_event), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_5event_event, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  __pyx_f_5event_5event___repr__, /*tp_repr*/
  &__pyx_tp_as_number_event, /*tp_as_number*/
  &__pyx_tp_as_sequence_event, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_event, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_event, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE|Py_TPFLAGS_HAVE_GC, /*tp_flags*/
  "event(callback, arg=None, evtype=0, handle=None) -> event object\n\n    Create a new event object with a user callback.\n\n    Arguments:\n\n    callback -- user callback with (event, handle, evtype, arg) prototype\n    arg      -- optional callback argument\n    evtype   -- bitmask of EV_READ or EV_WRITE, or EV_SIGNAL\n                XXX - for EV_SIGNAL, EV_PERSIST is implicit\n    handle   -- for EV_READ or EV_WRITE, a file handle or descriptor\n                for EV_SIGNAL, a signal number\n    ", /*tp_doc*/
  __pyx_tp_traverse_5event_event, /*tp_traverse*/
  __pyx_tp_clear_5event_event, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_5event_event, /*tp_methods*/
  0, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  __pyx_f_5event_5event___init__, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_5event_event, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static struct PyMethodDef __pyx_methods[] = {
  {"init", (PyCFunction)__pyx_f_5event_init, METH_VARARGS|METH_KEYWORDS, __pyx_doc_5event_init},
  {"add", (PyCFunction)__pyx_f_5event_add, METH_VARARGS|METH_KEYWORDS, __pyx_doc_5event_add},
  {"delete", (PyCFunction)__pyx_f_5event_delete, METH_VARARGS|METH_KEYWORDS, __pyx_doc_5event_delete},
  {"dispatch", (PyCFunction)__pyx_f_5event_dispatch, METH_VARARGS|METH_KEYWORDS, __pyx_doc_5event_dispatch},
  {"loop", (PyCFunction)__pyx_f_5event_loop, METH_VARARGS|METH_KEYWORDS, __pyx_doc_5event_loop},
  {0, 0, 0, 0}
};

DL_EXPORT(void) initevent(void); /*proto*/
DL_EXPORT(void) initevent(void) {
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  int __pyx_3;
  __pyx_m = Py_InitModule4("event", __pyx_methods, __pyx_mdoc, 0, PYTHON_API_VERSION);
  __pyx_b = PyImport_AddModule("__builtin__");
  PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b);
  if (PyType_Ready(&__pyx_type_5event_event) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "event", (PyObject *)&__pyx_type_5event_event) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; goto __pyx_L1;}
  __pyx_ptype_5event_event = &__pyx_type_5event_event;

  /* "/misc/projects/pyevent/event.pyx":18 */
  __pyx_1 = PyString_FromString(__pyx_k1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 18; goto __pyx_L1;}
  __pyx_2 = __Pyx_Import(__pyx_1, 0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 18; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  if (PyObject_SetAttrString(__pyx_m, "sys", __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 18; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/misc/projects/pyevent/event.pyx":47 */
  __pyx_1 = PyInt_FromLong(1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 47; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "EV_TIMEOUT", __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 47; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/misc/projects/pyevent/event.pyx":48 */
  __pyx_2 = PyInt_FromLong(2); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 48; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "EV_READ", __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 48; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/misc/projects/pyevent/event.pyx":49 */
  __pyx_1 = PyInt_FromLong(4); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 49; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "EV_WRITE", __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 49; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/misc/projects/pyevent/event.pyx":50 */
  __pyx_2 = PyInt_FromLong(8); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 50; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "EV_SIGNAL", __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 50; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/misc/projects/pyevent/event.pyx":51 */
  __pyx_1 = PyInt_FromLong(16); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 51; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "EV_PERSIST", __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 51; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/misc/projects/pyevent/event.pyx":53 */
  if (PyObject_SetAttrString(__pyx_m, "__event_exc", Py_None) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 53; goto __pyx_L1;}

  /* "/misc/projects/pyevent/event.pyx":80 */
  Py_INCREF(Py_None);
  __pyx_k2 = Py_None;
  __pyx_k3 = 0;
  __pyx_2 = PyInt_FromLong((-1)); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 80; goto __pyx_L1;}
  __pyx_k4 = __pyx_2;
  __pyx_2 = 0;

  /* "/misc/projects/pyevent/event.pyx":107 */
  __pyx_k5 = 0.0;

  /* "/misc/projects/pyevent/event.pyx":148 */
  __pyx_k6 = 0;

  /* "/misc/projects/pyevent/event.pyx":163 */
  __pyx_1 = __Pyx_GetName(__pyx_b, "False"); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 163; goto __pyx_L1;}
  __pyx_k7 = __pyx_1;
  __pyx_1 = 0;

  /* "/misc/projects/pyevent/event.pyx":171 */
  __pyx_3 = (!__pyx_v_5event___event_inited);
  if (__pyx_3) {

    /* "/misc/projects/pyevent/event.pyx":173 */
    event_init();
    goto __pyx_L3;
  }
  __pyx_L3:;
  return;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("event");
}

static char *__pyx_filenames[] = {
  "/misc/projects/pyevent/event.pyx",
};
statichere char **__pyx_f = __pyx_filenames;

/* Runtime support code */

static int __Pyx_ArgTypeTest(PyObject *obj, PyTypeObject *type, int none_allowed, char *name) {
	if (!type) {
		PyErr_Format(PyExc_SystemError, "Missing type object");
		return 0;
	}
	if ((none_allowed && obj == Py_None) || PyObject_TypeCheck(obj, type))
		return 1;
	PyErr_Format(PyExc_TypeError,
		"Argument '%s' has incorrect type (expected %s, got %s)",
		name, type->tp_name, obj->ob_type->tp_name);
	return 0;
}

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list) {
	PyObject *__import__ = 0;
	PyObject *empty_list = 0;
	PyObject *module = 0;
	PyObject *global_dict = 0;
	PyObject *empty_dict = 0;
	PyObject *list;
	__import__ = PyObject_GetAttrString(__pyx_b, "__import__");
	if (!__import__)
		goto bad;
	if (from_list)
		list = from_list;
	else {
		empty_list = PyList_New(0);
		if (!empty_list)
			goto bad;
		list = empty_list;
	}
	global_dict = PyModule_GetDict(__pyx_m);
	if (!global_dict)
		goto bad;
	empty_dict = PyDict_New();
	if (!empty_dict)
		goto bad;
	module = PyObject_CallFunction(__import__, "OOOO",
		name, global_dict, empty_dict, list);
bad:
	Py_XDECREF(empty_list);
	Py_XDECREF(__import__);
	Py_XDECREF(empty_dict);
	return module;
}

static PyObject *__Pyx_GetName(PyObject *dict, char *name) {
	PyObject *result;
	result = PyObject_GetAttrString(dict, name);
	if (!result)
		PyErr_SetString(PyExc_NameError, name);
	return result;
}

static void __Pyx_WriteUnraisable(char *name) {
	PyObject *old_exc, *old_val, *old_tb;
	PyObject *ctx;
	PyErr_Fetch(&old_exc, &old_val, &old_tb);
	ctx = PyString_FromString(name);
	PyErr_Restore(old_exc, old_val, old_tb);
	if (!ctx)
		ctx = Py_None;
	PyErr_WriteUnraisable(ctx);
}

static PyObject *__Pyx_GetExcValue(void) {
	PyObject *type = 0, *value = 0, *tb = 0;
	PyObject *result = 0;
	PyThreadState *tstate = PyThreadState_Get();
	PyErr_Fetch(&type, &value, &tb);
	PyErr_NormalizeException(&type, &value, &tb);
	if (PyErr_Occurred())
		goto bad;
	if (!value) {
		value = Py_None;
		Py_INCREF(value);
	}
	Py_XDECREF(tstate->exc_type);
	Py_XDECREF(tstate->exc_value);
	Py_XDECREF(tstate->exc_traceback);
	tstate->exc_type = type;
	tstate->exc_value = value;
	tstate->exc_traceback = tb;
	result = value;
	Py_XINCREF(result);
	type = 0;
	value = 0;
	tb = 0;
bad:
	Py_XDECREF(type);
	Py_XDECREF(value);
	Py_XDECREF(tb);
	return result;
}

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb) {
	Py_XINCREF(type);
	Py_XINCREF(value);
	Py_XINCREF(tb);
	/* First, check the traceback argument, replacing None with NULL. */
	if (tb == Py_None) {
		Py_DECREF(tb);
		tb = 0;
	}
	else if (tb != NULL && !PyTraceBack_Check(tb)) {
		PyErr_SetString(PyExc_TypeError,
			"raise: arg 3 must be a traceback or None");
		goto raise_error;
	}
	/* Next, replace a missing value with None */
	if (value == NULL) {
		value = Py_None;
		Py_INCREF(value);
	}
	/* Next, repeatedly, replace a tuple exception with its first item */
	while (PyTuple_Check(type) && PyTuple_Size(type) > 0) {
		PyObject *tmp = type;
		type = PyTuple_GET_ITEM(type, 0);
		Py_INCREF(type);
		Py_DECREF(tmp);
	}
	if (PyString_Check(type))
		;
	else if (PyClass_Check(type))
		; /*PyErr_NormalizeException(&type, &value, &tb);*/
	else if (PyInstance_Check(type)) {
		/* Raising an instance.  The value should be a dummy. */
		if (value != Py_None) {
			PyErr_SetString(PyExc_TypeError,
			  "instance exception may not have a separate value");
			goto raise_error;
		}
		else {
			/* Normalize to raise <class>, <instance> */
			Py_DECREF(value);
			value = type;
			type = (PyObject*) ((PyInstanceObject*)type)->in_class;
			Py_INCREF(type);
		}
	}
	else {
		/* Not something you can raise.  You get an exception
		   anyway, just not what you specified :-) */
		PyErr_Format(PyExc_TypeError,
			     "exceptions must be strings, classes, or "
			     "instances, not %s", type->ob_type->tp_name);
		goto raise_error;
	}
	PyErr_Restore(type, value, tb);
	return;
raise_error:
	Py_XDECREF(value);
	Py_XDECREF(type);
	Py_XDECREF(tb);
	return;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
	PyObject *py_srcfile = 0;
	PyObject *py_funcname = 0;
	PyObject *py_globals = 0;
	PyObject *empty_tuple = 0;
	PyObject *empty_string = 0;
	PyCodeObject *py_code = 0;
	PyFrameObject *py_frame = 0;
	
	py_srcfile = PyString_FromString(__pyx_filename);
	if (!py_srcfile) goto bad;
	py_funcname = PyString_FromString(funcname);
	if (!py_funcname) goto bad;
	py_globals = PyModule_GetDict(__pyx_m);
	if (!py_globals) goto bad;
	empty_tuple = PyTuple_New(0);
	if (!empty_tuple) goto bad;
	empty_string = PyString_FromString("");
	if (!empty_string) goto bad;
	py_code = PyCode_New(
		0,            /*int argcount,*/
		0,            /*int nlocals,*/
		0,            /*int stacksize,*/
		0,            /*int flags,*/
		empty_string, /*PyObject *code,*/
		empty_tuple,  /*PyObject *consts,*/
		empty_tuple,  /*PyObject *names,*/
		empty_tuple,  /*PyObject *varnames,*/
		empty_tuple,  /*PyObject *freevars,*/
		empty_tuple,  /*PyObject *cellvars,*/
		py_srcfile,   /*PyObject *filename,*/
		py_funcname,  /*PyObject *name,*/
		__pyx_lineno,   /*int firstlineno,*/
		empty_string  /*PyObject *lnotab*/
	);
	if (!py_code) goto bad;
	py_frame = PyFrame_New(
		PyThreadState_Get(), /*PyThreadState *tstate,*/
		py_code,             /*PyCodeObject *code,*/
		py_globals,          /*PyObject *globals,*/
		0                    /*PyObject *locals*/
	);
	if (!py_frame) goto bad;
	py_frame->f_lineno = __pyx_lineno;
	PyTraceBack_Here(py_frame);
bad:
	Py_XDECREF(py_srcfile);
	Py_XDECREF(py_funcname);
	Py_XDECREF(empty_tuple);
	Py_XDECREF(empty_string);
	Py_XDECREF(py_code);
	Py_XDECREF(py_frame);
}
